spring:
  application:
    name: yixian
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.67.119/flower?useSSL=false&serverTimezone=UTC
    username: root
    password: wd199604070010!

server:
  port: 8080

mybatis:
  configuration:
    #日志等级
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名与下划线自动匹配
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.yixian.dto